### ISSUE TITLE
PTX assertion failure

### ISSUE THREAD

**Issue by stelleg** [lanl/kitsune-old#2]
running the PTX backend on the following loop fails with the error:
```
clang-5.0: /scratch/users/stelleg/tapir/kitsune/llvm/lib/Transforms/Tapir/PTXABI.cpp:280: virtual bool llvm::PTXABILoopSpawning::processLoop(): Assertion `pt && "expected a pointer type"' failed.
```

The loop:
```
#pragma omp target parallel for
  for(int i=0; i<n; i++){
    a[i] = i;
  }
```

**Comment by stelleg** [comment]
Failed because it was a stack allocated array reference, which we probably don't need to worry about for now.

**Comment by nickm319** [comment]
It currently only supports heap allocated arrays.  this is something in general we need to address as a group to define what types of data structures we want support for various front ends. the issue here is that I need to know the size of the array to perform the data copies. currently I just extract the size from the call to allocate memory.
